// v0_source/components/small-winner-ticker.tsx
"use client"

import { Trophy, Zap } from "lucide-react"
import { useEffect, useState } from "react"
import { cn } from "@/lib/utils"

const mockWins = [
  { user: "Player***89", game: "Hash Dice", amount: "0.45 BTC", multiplier: "12.5x", time: "Just now" },
  { user: "Crypto***23", game: "Mega Roulette", amount: "1.2 ETH", multiplier: "35x", time: "1m ago" },
  { user: "Whale***56", game: "Aviator", amount: "2.8 BTC", multiplier: "48.3x", time: "2m ago" },
  { user: "Lucky***91", game: "Plinko", amount: "0.87 BTC", multiplier: "21x", time: "3m ago" },
  { user: "High***42", game: "Crash", amount: "1.5 BTC", multiplier: "28.7x", time: "4m ago" },
  { user: "Pro***12", game: "Sweet Bonanza", amount: "0.95 ETH", multiplier: "15.2x", time: "5m ago" },
  { user: "Win***77", game: "Limbo", amount: "0.63 BTC", multiplier: "18.9x", time: "6m ago" },
  { user: "Bet***34", game: "Mines", amount: "1.1 BTC", multiplier: "24.6x", time: "7m ago" },
  { user: "King***99", game: "Blackjack", amount: "0.78 ETH", multiplier: "2x", time: "8m ago" },
  { user: "Fast***45", game: "Crazy Time", amount: "3.2 BTC", multiplier: "52.1x", time: "9m ago" },
  { user: "Luck***88", game: "Wheel", amount: "0.54 BTC", multiplier: "11.3x", time: "10m ago" },
  { user: "Ace***67", game: "Dice", amount: "1.8 ETH", multiplier: "32.5x", time: "11m ago" },
  { user: "Boss***21", game: "Plinko", amount: "0.92 BTC", multiplier: "19.7x", time: "12m ago" },
  { user: "Max***53", game: "Slots", amount: "1.4 BTC", multiplier: "25.8x", time: "13m ago" },
  { user: "Top***76", game: "Baccarat", amount: "0.68 ETH", multiplier: "1.95x", time: "14m ago" },
]

export default function SmallWinnerTicker() {
  const [wins, setWins] = useState(mockWins)
  const [newWinId, setNewWinId] = useState<number | null>(null)

  useEffect(() => {
    const interval = setInterval(() => {
      // Simulate new win
      const newWin = {
        user: `User***${Math.floor(Math.random() * 100)}`,
        game: ["Hash Dice", "Aviator", "Plinko", "Crash", "Roulette"][Math.floor(Math.random() * 5)],
        amount: `${(Math.random() * 3).toFixed(2)} ${Math.random() > 0.5 ? "BTC" : "ETH"}`,
        multiplier: `${(Math.random() * 50 + 1).toFixed(1)}x`,
        time: "Just now",
      }
      setWins((prev) => [newWin, ...prev.slice(0, 14)])
      setNewWinId(Date.now())
      setTimeout(() => setNewWinId(null), 1000)
    }, 8000)
    return () => clearInterval(interval)
  }, [])

  return (
    <div className="bg-card/40 backdrop-blur-sm border border-border/50 rounded-md p-2 md:p-2.5">
      <div className="flex items-center gap-2 mb-2">
        <div className="flex h-7 w-7 items-center justify-center rounded-md bg-gradient-to-br from-primary/30 to-accent/30 border border-primary/50">
          <Trophy className="h-3.5 w-3.5 text-primary" />
        </div>
        <div>
          <h3 className="text-[13px] font-bold text-foreground">Latest Wins</h3>
          <p className="text-[10px] text-muted-foreground">Live results from players</p>
        </div>
      </div>

      {/* Vertical scrollable list - shows 5-6 at a time */}
      <div className="space-y-1 max-h-[240px] overflow-y-auto scrollbar-thin scrollbar-thumb-border/50 scrollbar-track-transparent pr-1">
        {wins.map((win, index) => (
          <div
            key={index}
            className={cn(
              "flex items-center justify-between gap-2 p-1.5 rounded-md bg-secondary/30 border border-transparent transition-all duration-300",
              index === 0 && newWinId && "border-primary/50 bg-primary/10",
            )}
          >
            <div className="flex items-center gap-2 flex-1 min-w-0">
              <div className="flex h-5 w-5 items-center justify-center rounded bg-gradient-to-br from-accent/20 to-accent-secondary/20">
                <Zap className="h-2.5 w-2.5 text-accent" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-1.5">
                  <span className="text-[11px] font-semibold text-foreground truncate">{win.user}</span>
                  <span className="text-[10px] text-muted-foreground hidden sm:inline">won</span>
                </div>
                <span className="text-[10px] text-muted-foreground truncate block">{win.game}</span>
              </div>
            </div>

            <div className="flex items-center gap-2 shrink-0">
              <div className="text-right">
                <div className="text-[11px] font-bold text-primary">{win.amount}</div>
                <div className="text-[9px] text-muted-foreground">{win.time}</div>
              </div>
              <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-gradient-to-r from-accent/20 to-accent-secondary/20 border border-accent/50 text-accent">
                {win.multiplier}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// frontend-vue3/src/components/common/SmallWinnerTicker.vue
<template>
  <div class="winner-ticker">
    <div class="ticker-header">
      <div class="header-icon">
        <Trophy class="icon" />
      </div>
      <div>
        <h3 class="ticker-title">Latest Wins</h3>
        <p class="ticker-subtitle">Live results from players</p>
      </div>
    </div>

    <div class="ticker-list" ref="listRef">
      <div
        v-for="(win, index) in wins"
        :key="win.id || index"
        class="ticker-item"
        :class="{ 'is-new': win.isNew }"
      >
        <div class="ticker-item-left">
          <div class="item-icon">
            <Lightning class="icon-small" />
          </div>
          <div class="item-info">
            <div class="item-user-row">
              <span class="item-user">{{ win.user }}</span>
              <span class="item-won-text">won</span>
            </div>
            <span class="item-game">{{ win.game }}</span>
          </div>
        </div>
        <div class="ticker-item-right">
          <div class="item-amount">{{ win.amount }}</div>
          <div class="item-time">{{ win.time }}</div>
        </div>
        <span v-if="win.multiplier" class="item-multiplier">
          {{ win.multiplier }}
        </span>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { Trophy, Lightning } from '@element-plus/icons-vue'
import { useSocket } from '@/composables/useSocket.js'
import { getToken } from '@/store/index.js'

const wins = ref([])
const listRef = ref(null)
let socket = null

function formatUserDisplayName(username) {
  if (!username) return 'Anonymous***'
  if (username.length <= 6) return username + '***'
  const visible = username.substring(0, 3)
  return visible + '***' + username.substring(username.length - 2)
}

function formatAmount(amount) {
  const num = parseFloat(amount)
  if (isNaN(num)) return '0 USDT'
  if (num >= 1) {
    return num.toFixed(2) + ' USDT'
  }
  return num.toFixed(4) + ' USDT'
}

function formatTimeAgo(timestamp) {
  if (!timestamp) return 'Just now'
  const seconds = Math.floor((Date.now() - timestamp) / 1000)
  if (seconds < 60) return 'Just now'
  const minutes = Math.floor(seconds / 60)
  if (minutes < 60) return `${minutes}m ago`
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `${hours}h ago`
  const days = Math.floor(hours / 24)
  return `${days}d ago`
}

function addWin(winData) {
  const win = {
    id: Date.now() + Math.random(),
    user: formatUserDisplayName(winData.username || winData.user),
    game: winData.game || 'Flip Coin',
    amount: formatAmount(winData.amount || winData.win_amount || 0),
    multiplier: winData.multiplier ? `${winData.multiplier}x` : null,
    time: formatTimeAgo(winData.timestamp || winData.bet_time),
    timestamp: winData.timestamp || winData.bet_time || Date.now(),
    isNew: true
  }
  
  wins.value.unshift(win)
  
  if (wins.value.length > 15) {
    wins.value = wins.value.slice(0, 15)
  }
  
  setTimeout(() => {
    const winIndex = wins.value.findIndex(w => w.id === win.id)
    if (winIndex !== -1) {
      wins.value[winIndex].isNew = false
    }
  }, 1000)
}

function initializeSocketListener() {
  const token = getToken()
  if (!token) return
  
  const { initializeSocket, getSocket } = useSocket()
  
  socket = initializeSocket(token, {
    onBetUpdated: (betData) => {
      if (betData.status === 'won' && betData.amount) {
        addWin({
          username: betData.username,
          game: 'Flip Coin',
          amount: betData.amount * 2,
          multiplier: '2x',
          timestamp: new Date(betData.settled_at || Date.now()).getTime()
        })
      }
    },
    onLeaderboardUpdated: (data) => {
      if (Array.isArray(data) && data.length > 0) {
        const latestWinner = data[0]
        if (latestWinner && latestWinner.max_streak > 0) {
          addWin({
            username: latestWinner.username || latestWinner.display_name,
            game: 'Flip Coin',
            amount: 'N/A',
            timestamp: Date.now()
          })
        }
      }
    }
  })
}

onMounted(() => {
  initializeSocketListener()
  
  setTimeout(() => {
    initializeSocketListener()
  }, 1000)
})

onUnmounted(() => {
  if (socket) {
    socket.disconnect()
  }
})
</script>

<style scoped>
.winner-ticker {
  background-color: rgba(26, 28, 31, 0.4);
  backdrop-filter: blur(8px);
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  padding: var(--space-2);
}

@media (min-width: 768px) {
  .winner-ticker {
    padding: calc(var(--space-2) + var(--space-1));
  }
}

.ticker-header {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  margin-bottom: var(--space-2);
}

.header-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border-radius: var(--radius-md);
  background: linear-gradient(135deg, rgba(243, 195, 64, 0.3), rgba(138, 108, 244, 0.3));
  border: 1px solid rgba(243, 195, 64, 0.5);
}

.header-icon .icon {
  width: 14px;
  height: 14px;
  color: var(--primary);
}

.ticker-title {
  font-size: 13px;
  font-weight: 700;
  color: var(--foreground);
  margin: 0;
  line-height: 1.2;
}

.ticker-subtitle {
  font-size: 10px;
  color: var(--text-muted);
  margin: 0;
  line-height: 1.2;
}

.ticker-list {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
  max-height: 240px;
  overflow-y: auto;
  padding-right: var(--space-1);
}

.ticker-list::-webkit-scrollbar {
  width: 4px;
}

.ticker-list::-webkit-scrollbar-track {
  background: transparent;
}

.ticker-list::-webkit-scrollbar-thumb {
  background-color: var(--border);
  border-radius: 2px;
}

.ticker-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-2);
  padding: var(--space-2);
  border-radius: var(--radius-md);
  background-color: rgba(138, 108, 244, 0.3);
  border: 1px solid transparent;
  transition: all 0.3s;
}

.ticker-item.is-new {
  border-color: rgba(243, 195, 64, 0.5);
  background-color: rgba(243, 195, 64, 0.1);
}

.ticker-item-left {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  flex: 1;
  min-width: 0;
}

.item-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 20px;
  height: 20px;
  border-radius: var(--radius-sm);
  background: linear-gradient(135deg, rgba(138, 108, 244, 0.2), rgba(107, 76, 230, 0.2));
}

.icon-small {
  width: 10px;
  height: 10px;
  color: var(--accent);
}

.item-info {
  flex: 1;
  min-width: 0;
}

.item-user-row {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  margin-bottom: 2px;
}

.item-user {
  font-size: 11px;
  font-weight: 600;
  color: var(--foreground);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.item-won-text {
  font-size: 10px;
  color: var(--text-muted);
  display: none;
}

@media (min-width: 640px) {
  .item-won-text {
    display: inline;
  }
}

.item-game {
  display: block;
  font-size: 10px;
  color: var(--text-muted);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.ticker-item-right {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 2px;
  flex-shrink: 0;
}

.item-amount {
  font-size: 11px;
  font-weight: 700;
  color: var(--primary);
  line-height: 1.2;
}

.item-time {
  font-size: 9px;
  color: var(--text-muted);
  line-height: 1.2;
}

.item-multiplier {
  font-size: 10px;
  font-weight: 700;
  padding: 2px var(--space-2);
  border-radius: var(--radius-sm);
  background: linear-gradient(135deg, rgba(138, 108, 244, 0.2), rgba(107, 76, 230, 0.2));
  border: 1px solid rgba(138, 108, 244, 0.5);
  color: var(--accent);
  flex-shrink: 0;
}
</style>
