// v0_source/components/mobile-bottom-nav.tsx
"use client"

import { Home, Menu, MessageCircle, User, Wallet } from "lucide-react"
import { useState } from "react"
import SidebarDrawer from "./sidebar-drawer"
import WalletModal from "./wallet-modal"

const navItems = [
  { icon: Menu, label: "Menu", id: "menu" },
  { icon: Home, label: "Home", id: "home" },
  { icon: Wallet, label: "Deposit", id: "deposit", highlight: true },
  { icon: MessageCircle, label: "Chat", id: "chat" },
  { icon: User, label: "Me", id: "me" },
]

export default function MobileBottomNav() {
  const [activeTab, setActiveTab] = useState("home")
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [walletOpen, setWalletOpen] = useState(false)

  const handleNavClick = (id: string) => {
    setActiveTab(id)
    if (id === "menu") {
      setSidebarOpen(true)
    } else if (id === "deposit") {
      setWalletOpen(true)
    }
  }

  return (
    <>
      <nav className="fixed bottom-0 left-0 right-0 z-50 md:hidden border-t border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80">
        <div className="grid grid-cols-5 h-12">
          {navItems.map((item) => {
            const Icon = item.icon
            const isActive = activeTab === item.id

            return (
              <button
                key={item.id}
                onClick={() => handleNavClick(item.id)}
                className={`flex flex-col items-center justify-center gap-0.5 transition-colors ${
                  item.highlight
                    ? "relative"
                    : isActive
                      ? "text-primary"
                      : "text-muted-foreground hover:text-foreground"
                }`}
              >
                {item.highlight ? (
                  <div className="absolute -top-2.5 flex h-10 w-10 items-center justify-center rounded-full bg-primary shadow-lg shadow-primary/50">
                    <Icon className="h-[18px] w-[18px] text-primary-foreground" />
                  </div>
                ) : (
                  <>
                    <Icon className="h-[18px] w-[18px]" />
                    <span className="text-[9px] font-medium">{item.label}</span>
                  </>
                )}
              </button>
            )
          })}
        </div>
      </nav>

      <SidebarDrawer open={sidebarOpen} onOpenChange={setSidebarOpen} />
      <WalletModal open={walletOpen} onOpenChange={setWalletOpen} />
    </>
  )
}

// frontend-vue3/src/components/layout/MobileBottomNav.vue
<template>
  <nav class="mobile-bottom-nav">
    <div class="nav-grid">
      <button
        v-for="item in navItems"
        :key="item.id"
        @click="handleNavClick(item.id)"
        :class="['nav-item', { active: activeTab === item.id, highlight: item.highlight }]"
      >
        <div v-if="item.highlight" class="highlight-button">
          <component :is="item.icon" class="nav-icon" />
        </div>
        <template v-else>
          <component :is="item.icon" class="nav-icon" />
          <span class="nav-label">{{ item.label }}</span>
        </template>
      </button>
    </div>
  </nav>
</template>

<script setup>
import { ref } from 'vue'
import { Grid, ChatDotRound, User, Wallet } from '@element-plus/icons-vue'

const props = defineProps({
  onMenuClick: Function,
  onDepositClick: Function
})

const activeTab = ref('home')

const navItems = [
  { icon: Grid, label: 'Menu', id: 'menu' },
  { icon: Grid, label: 'Home', id: 'home' },
  { icon: Wallet, label: 'Deposit', id: 'deposit', highlight: true },
  { icon: ChatDotRound, label: 'Chat', id: 'chat' },
  { icon: User, label: 'Me', id: 'me' }
]

function handleNavClick(id) {
  activeTab.value = id
  if (id === 'menu' && props.onMenuClick) {
    props.onMenuClick()
  } else if (id === 'deposit' && props.onDepositClick) {
    props.onDepositClick()
  }
}
</script>

<style scoped>
.mobile-bottom-nav {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 50;
  border-top: 1px solid var(--border);
  background-color: rgba(19, 20, 22, 0.95);
  backdrop-filter: blur(8px);
  display: block;
}

@media (min-width: 768px) {
  .mobile-bottom-nav {
    display: none;
  }
}

.nav-grid {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  height: 48px;
}

.nav-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2px;
  transition: color 0.2s;
  background: transparent;
  border: none;
  cursor: pointer;
  color: var(--text-muted);
  position: relative;
}

.nav-item.active {
  color: var(--primary);
}

.nav-item.highlight {
  position: relative;
}

.highlight-button {
  position: absolute;
  top: -10px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background-color: var(--primary);
  box-shadow: 0 4px 12px rgba(243, 195, 64, 0.5);
}

.highlight-button .nav-icon {
  color: var(--surface);
}

.nav-icon {
  width: 18px;
  height: 18px;
}

.nav-label {
  font-size: 9px;
  font-weight: 500;
}
</style>
