// v0_source/components/top-category-nav.tsx
"use client"

import { useState } from "react"
import { Home, Trophy, Radio, Dices, Plane, Clapperboard, Hash, Gamepad2, Swords, Monitor, Gift } from "lucide-react"
import { cn } from "@/lib/utils"

const categories = [
  { id: "home", label: "Home", icon: Home },
  { id: "sports", label: "Sports", icon: Trophy },
  { id: "live", label: "Live", icon: Radio },
  { id: "casino", label: "Casino", icon: Dices },
  { id: "aviator", label: "Aviator", icon: Plane },
  { id: "live-casino", label: "Live Casino", icon: Clapperboard },
  { id: "lucky-numbers", label: "Lucky Numbers", icon: Hash },
  { id: "betgames", label: "BetGames", icon: Gamepad2 },
  { id: "esports", label: "Esports", icon: Swords },
  { id: "virtuals", label: "Virtuals", icon: Monitor },
  { id: "promotions", label: "Promotions", icon: Gift },
]

export default function TopCategoryNav() {
  const [activeCategory, setActiveCategory] = useState("home")

  return (
    <div className="sticky top-[38px] md:top-[44px] z-40 border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80">
      <div className="hidden lg:block">
        <div className="mx-auto max-w-[1280px] px-4">
          <div className="flex items-center">
            {categories.map((category) => {
              const Icon = category.icon
              const isActive = activeCategory === category.id

              return (
                <button
                  key={category.id}
                  onClick={() => setActiveCategory(category.id)}
                  className={cn(
                    "flex items-center gap-1.5 px-3 h-10 text-[13px] font-medium transition-all relative",
                    isActive ? "text-primary" : "text-muted-foreground hover:text-foreground hover:bg-secondary/30",
                  )}
                >
                  <Icon className="w-[16px] h-[16px]" />
                  <span>{category.label}</span>
                  {isActive && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-primary rounded-t-full" />}
                </button>
              )
            })}
          </div>
        </div>
      </div>

      <div className="lg:hidden overflow-x-auto scrollbar-hide">
        <div className="flex items-center gap-0.5 px-2 md:px-3 min-w-max">
          {categories.map((category) => {
            const Icon = category.icon
            const isActive = activeCategory === category.id

            return (
              <button
                key={category.id}
                onClick={() => setActiveCategory(category.id)}
                className={cn(
                  "flex items-center gap-1 px-2 md:px-2.5 h-9 md:h-9 text-[11px] md:text-[12px] font-medium transition-all whitespace-nowrap relative",
                  isActive ? "text-primary" : "text-muted-foreground",
                )}
              >
                <Icon className="w-[14px] md:w-[15px] h-[14px] md:h-[15px]" />
                <span>{category.label}</span>
                {isActive && <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-primary rounded-t-full" />}
              </button>
            )
          })}
        </div>
      </div>
    </div>
  )
}

// frontend-vue3/src/components/layout/TopCategoryNav.vue
<template>
  <div class="top-category-nav">
    <!-- Desktop -->
    <div class="category-nav-desktop">
      <div class="category-nav-container">
        <button
          v-for="category in categories"
          :key="category.id"
          @click="setActiveCategory(category.id)"
          :class="['category-item', { active: activeCategory === category.id }]"
        >
          <component :is="category.icon" class="category-icon" />
          <span>{{ category.label }}</span>
          <div v-if="activeCategory === category.id" class="active-indicator" />
        </button>
      </div>
    </div>

    <!-- Mobile -->
    <div class="category-nav-mobile">
      <div class="category-nav-scroll">
        <button
          v-for="category in categories"
          :key="category.id"
          @click="setActiveCategory(category.id)"
          :class="['category-item', { active: activeCategory === category.id }]"
        >
          <component :is="category.icon" class="category-icon" />
          <span>{{ category.label }}</span>
          <div v-if="activeCategory === category.id" class="active-indicator" />
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import {
  Grid,
  Trophy,
  VideoPlay,
  Box,
  Promotion,
  VideoCamera,
  Key,
  Coin,
  DataLine,
  Monitor,
  Present
} from '@element-plus/icons-vue'

const props = defineProps({
  modelValue: {
    type: String,
    default: 'home'
  }
})

const emit = defineEmits(['update:modelValue'])

const activeCategory = ref(props.modelValue)

const categories = [
  { id: 'home', label: 'Home', icon: Grid },
  { id: 'sports', label: 'Sports', icon: Trophy },
  { id: 'live', label: 'Live', icon: VideoPlay },
  { id: 'casino', label: 'Casino', icon: Box },
  { id: 'aviator', label: 'Aviator', icon: Promotion },
  { id: 'live-casino', label: 'Live Casino', icon: VideoCamera },
  { id: 'lucky-numbers', label: 'Lucky Numbers', icon: Key },
  { id: 'betgames', label: 'BetGames', icon: Coin },
  { id: 'esports', label: 'Esports', icon: DataLine },
  { id: 'virtuals', label: 'Virtuals', icon: Monitor },
  { id: 'promotions', label: 'Promotions', icon: Present }
]

function setActiveCategory(id) {
  activeCategory.value = id
  emit('update:modelValue', id)
}
</script>

<style scoped>
.top-category-nav {
  position: sticky;
  top: 56px;
  z-index: 40;
  border-bottom: 1px solid var(--border);
  background-color: rgba(19, 20, 22, 0.95);
  backdrop-filter: blur(8px);
}

.category-nav-desktop {
  display: none;
}

@media (min-width: 1024px) {
  .category-nav-desktop {
    display: block;
  }
}

.category-nav-container {
  max-width: 1280px;
  margin: 0 auto;
  padding: 0 var(--space-4);
  display: flex;
  align-items: center;
}

.category-nav-mobile {
  display: block;
  overflow-x: auto;
  scrollbar-width: none;
  -ms-overflow-style: none;
}

.category-nav-mobile::-webkit-scrollbar {
  display: none;
}

@media (min-width: 1024px) {
  .category-nav-mobile {
    display: none;
  }
}

.category-nav-scroll {
  display: flex;
  align-items: center;
  gap: 2px;
  padding: 0 var(--space-2);
  min-width: max-content;
}

.category-item {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: 0 var(--space-3);
  height: 40px;
  font-size: 13px;
  font-weight: 500;
  transition: all 0.2s;
  background: transparent;
  border: none;
  cursor: pointer;
  color: var(--text-muted);
  position: relative;
  white-space: nowrap;
}

.category-item:hover {
  color: var(--foreground);
  background-color: rgba(26, 28, 31, 0.3);
}

.category-item.active {
  color: var(--primary);
}

.category-icon {
  width: 16px;
  height: 16px;
}

.active-indicator {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  height: 2px;
  background-color: var(--primary);
  border-radius: 2px 2px 0 0;
}

.category-nav-mobile .category-item {
  padding: 0 var(--space-2);
  height: 36px;
  font-size: 11px;
}

.category-nav-mobile .category-icon {
  width: 14px;
  height: 14px;
}
</style>
