// frontend-vue3/src/components/layout/CompactHeroStrip.vue
<template>
  <section class="hero-strip">
    <div class="hero-content">
      <div class="hero-left">
        <div class="hero-badges">
          <span class="badge badge-primary">
            <Lightning class="badge-icon" />
            Provably Fair
          </span>
          <span class="badge badge-secondary">
            <TrendCharts class="badge-icon" />
            $2.5M Daily Volume
          </span>
          <span class="badge badge-success">
            <Trophy class="badge-icon" />
            10,000+ Winners Today
          </span>
        </div>
        <h1 class="hero-title">
          <span class="gradient-text">Win Big</span> with Crypto Fairness
        </h1>
        <p class="hero-subtitle">
          Transparent blockchain gaming • Instant crypto payouts • Every bet verifiable on-chain
        </p>
      </div>
      <div class="hero-right">
        <button class="cta-button primary" @click="handleSignUp">
          Sign Up Now
        </button>
        <button class="cta-button secondary" @click="handleDemo">
          Quick Demo
        </button>
      </div>
    </div>
  </section>
</template>

<script setup>
import { Lightning, TrendCharts, Trophy } from '@element-plus/icons-vue'

const emit = defineEmits(['signup', 'demo'])

function handleSignUp() {
  emit('signup')
}

function handleDemo() {
  emit('demo')
}
</script>

<style scoped>
.hero-strip {
  position: relative;
  overflow: hidden;
  background: linear-gradient(to right, rgba(243, 195, 64, 0.2), rgba(138, 108, 244, 0.2));
  border-bottom: 1px solid var(--border);
}

.hero-strip::before {
  content: '';
  position: absolute;
  inset: 0;
  opacity: 0.3;
  background: linear-gradient(135deg, rgba(138, 108, 244, 0.4), rgba(243, 195, 64, 0.3));
  filter: blur(120px);
}

.hero-content {
  position: relative;
  max-width: 1400px;
  margin: 0 auto;
  padding: var(--space-3) var(--space-4);
  min-height: 140px;
  display: flex;
  align-items: center;
  gap: var(--space-4);
  flex-wrap: wrap;
}

@media (min-width: 768px) {
  .hero-content {
    min-height: 180px;
    padding: var(--space-4);
  }
}

@media (min-width: 1024px) {
  .hero-content {
    flex-wrap: nowrap;
    grid-template-columns: 1fr auto;
  }
}

.hero-left {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
  min-width: 0;
}

@media (min-width: 768px) {
  .hero-left {
    gap: calc(var(--space-2) + var(--space-1));
  }
}

.hero-badges {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  flex-wrap: wrap;
}

.badge {
  display: inline-flex;
  align-items: center;
  gap: var(--space-1);
  height: 20px;
  padding: 0 calc(var(--space-2) + var(--space-1));
  font-size: 10px;
  font-weight: 500;
  border-radius: var(--radius-sm);
  border: 1px solid;
}

.badge-primary {
  background-color: rgba(138, 108, 244, 0.3);
  color: var(--accent-foreground);
  border-color: rgba(138, 108, 244, 0.6);
}

.badge-secondary {
  background-color: rgba(243, 195, 64, 0.3);
  color: var(--primary-foreground);
  border-color: rgba(243, 195, 64, 0.6);
}

.badge-success {
  background-color: rgba(40, 192, 129, 0.3);
  color: #28C081;
  border-color: rgba(40, 192, 129, 0.6);
}

.badge-icon {
  width: 10px;
  height: 10px;
}

.hero-title {
  font-size: 20px;
  font-weight: 700;
  color: var(--foreground);
  margin: 0;
  line-height: 1.2;
}

@media (min-width: 768px) {
  .hero-title {
    font-size: 30px;
  }
}

@media (min-width: 1024px) {
  .hero-title {
    font-size: 36px;
  }
}

.gradient-text {
  background: linear-gradient(to right, var(--primary), var(--accent), var(--accent-secondary));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.hero-subtitle {
  font-size: 12px;
  color: var(--text-muted);
  margin: 0;
  max-width: 600px;
}

@media (min-width: 768px) {
  .hero-subtitle {
    font-size: 13px;
  }
}

.hero-right {
  display: flex;
  flex-direction: row;
  gap: var(--space-2);
}

@media (min-width: 768px) {
  .hero-right {
    flex-direction: column;
  }
}

.cta-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: 36px;
  padding: 0 var(--space-5);
  font-size: 13px;
  font-weight: 700;
  border-radius: var(--radius-lg);
  border: none;
  cursor: pointer;
  transition: all 0.2s;
}

@media (min-width: 768px) {
  .cta-button {
    height: 44px;
    padding: 0 calc(var(--space-5) + var(--space-2));
    font-size: 14px;
  }
}

.cta-button.primary {
  background: linear-gradient(to right, var(--primary), var(--accent));
  color: var(--surface);
  box-shadow: 0 4px 12px rgba(243, 195, 64, 0.4);
}

.cta-button.primary:hover {
  opacity: 0.9;
  transform: translateY(-1px);
  box-shadow: 0 6px 16px rgba(243, 195, 64, 0.5);
}

.cta-button.secondary {
  background-color: rgba(26, 28, 31, 0.5);
  backdrop-filter: blur(8px);
  border: 1px solid rgba(138, 108, 244, 0.5);
  color: var(--foreground);
  font-weight: 600;
}

.cta-button.secondary:hover {
  background-color: rgba(138, 108, 244, 0.1);
  border-color: rgba(138, 108, 244, 0.7);
}
</style>

// v0_source/components/compact-hero-strip.tsx
"use client"

import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { TrendingUp, Zap, Trophy } from "lucide-react"
import Image from "next/image"

export default function CompactHeroStrip() {
  return (
    <section className="relative overflow-hidden bg-gradient-to-r from-primary/20 via-accent/20 to-accent-secondary/20 border-b border-border/50">
      {/* Background with overlay */}
      <div className="absolute inset-0">
        <Image
          src="/.jpg?height=220&width=1400&query=luxury casino background with neon lights and crypto symbols"
          alt="Casino banner"
          fill
          className="object-cover opacity-30"
        />
        <div className="absolute inset-0 bg-gradient-to-r from-background/95 via-background/80 to-background/60" />
      </div>

      {/* Accent blobs */}
      <div className="absolute inset-0 opacity-20">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-accent/40 rounded-full blur-[120px]" />
        <div className="absolute top-0 right-1/4 w-96 h-96 bg-primary/30 rounded-full blur-[120px]" />
      </div>

      <div className="relative mx-auto max-w-[1400px] px-3 md:px-4 h-[140px] md:h-[180px] flex items-center">
        <div className="grid md:grid-cols-[1fr_auto] gap-4 md:gap-6 w-full items-center">
          {/* Left Content */}
          <div className="space-y-2 md:space-y-2.5">
            <div className="flex items-center gap-1.5 flex-wrap">
              <Badge className="bg-accent/30 text-accent-foreground border-accent/60 text-[10px] px-1.5 py-0.5 h-5">
                <Zap className="w-2.5 h-2.5 mr-0.5" />
                Provably Fair
              </Badge>
              <Badge className="bg-primary/30 text-primary-foreground border-primary/60 text-[10px] px-1.5 py-0.5 h-5">
                <TrendingUp className="w-2.5 h-2.5 mr-0.5" />
                $2.5M Daily Volume
              </Badge>
              <Badge className="bg-green-500/30 text-green-400 border-green-500/60 text-[10px] px-1.5 py-0.5 h-5">
                <Trophy className="w-2.5 h-2.5 mr-0.5" />
                10,000+ Winners Today
              </Badge>
            </div>

            <h1 className="text-xl md:text-3xl lg:text-4xl font-bold text-balance leading-tight">
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-accent to-accent-secondary">
                Win Big
              </span>{" "}
              with Crypto Fairness
            </h1>

            <p className="text-[12px] md:text-[13px] text-muted-foreground text-pretty max-w-xl">
              Transparent blockchain gaming • Instant crypto payouts • Every bet verifiable on-chain
            </p>
          </div>

          {/* Right CTAs */}
          <div className="flex md:flex-col gap-2">
            <Button className="h-9 md:h-11 px-5 md:px-8 bg-gradient-to-r from-primary to-accent hover:opacity-90 shadow-lg shadow-primary/40 text-[13px] md:text-[14px] font-bold rounded-lg">
              Sign Up Now
            </Button>
            <Button
              variant="outline"
              className="h-9 md:h-11 px-5 md:px-8 border-accent/50 hover:bg-accent/10 bg-background/50 backdrop-blur text-[13px] md:text-[14px] font-semibold rounded-lg"
            >
              Quick Demo
            </Button>
          </div>
        </div>
      </div>
    </section>
  )
}
