// frontend-vue3/src/components/layout/Header.vue
<template>
  <header class="header">
    <div class="header-container">
      <div class="header-content">
        <!-- Logo -->
        <div class="logo">
          <div class="logo-icon">#</div>
          <span class="logo-text">{{ platformName }}</span>
        </div>

        <!-- Search Bar - Desktop only -->
        <div class="search-bar-desktop">
          <el-input
            v-model="searchQuery"
            placeholder="Search games..."
            class="search-input"
          >
            <template #prefix>
              <el-icon><Search /></el-icon>
            </template>
          </el-input>
        </div>

        <!-- Right Actions -->
        <div class="header-actions">
          <template v-if="isLoggedIn">
            <!-- Wallet Balance - Desktop -->
            <div class="wallet-balance-desktop">
              <el-icon><Wallet /></el-icon>
              <span>${{ formatBalance(currentUser?.balance) }}</span>
            </div>
            <el-button
              type="primary"
              @click="openWallet"
              class="deposit-btn"
            >
              Deposit
            </el-button>
            <el-button
              circle
              @click="openPersonalCenter"
              class="user-btn"
            >
              <el-icon><User /></el-icon>
            </el-button>
          </template>
          <template v-else>
            <el-button
              text
              @click="openLogin"
              class="login-btn-desktop"
            >
              <el-icon><UserFilled /></el-icon>
              Login
            </el-button>
            <el-button
              type="primary"
              @click="openRegister"
              class="signup-btn"
            >
              Sign Up
            </el-button>
          </template>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { Search, Wallet, User, UserFilled } from '@element-plus/icons-vue'
import { getCurrentUser, getToken } from '@/store/index.js'
import * as api from '@/api/index.js'

const props = defineProps({
  onWalletClick: Function,
  onPersonalCenterClick: Function,
  onLoginClick: Function,
  onRegisterClick: Function
})

const searchQuery = ref('')
const platformName = ref('FairHash')

const isLoggedIn = computed(() => {
  return !!getToken() && !!getCurrentUser()
})

const currentUser = computed(() => getCurrentUser())

function formatBalance(balance) {
  if (!balance) return '0.00'
  return parseFloat(balance).toFixed(2)
}

function openWallet() {
  if (props.onWalletClick) props.onWalletClick()
}

function openPersonalCenter() {
  if (props.onPersonalCenterClick) props.onPersonalCenterClick()
}

function openLogin() {
  if (props.onLoginClick) props.onLoginClick()
}

function openRegister() {
  if (props.onRegisterClick) props.onRegisterClick()
}

onMounted(async () => {
  try {
    const data = await api.getPlatformName()
    platformName.value = data.platform_name || 'FairHash'
    document.title = platformName.value
  } catch (error) {
    console.error('Failed to load platform name:', error)
  }
})
</script>

<style scoped>
.header {
  position: sticky;
  top: 0;
  z-index: 50;
  border-bottom: 1px solid var(--border);
  background-color: rgba(19, 20, 22, 0.95);
  backdrop-filter: blur(8px);
}

.header-container {
  max-width: 1400px;
  margin: 0 auto;
  padding: var(--space-2) var(--space-3);
}

.header-content {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-4);
}

.logo {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  flex-shrink: 0;
}

.logo-icon {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-md);
  background: linear-gradient(to bottom right, var(--accent), var(--accent-secondary));
  font-size: 13px;
  font-weight: bold;
  color: var(--foreground);
}

.logo-text {
  font-size: 16px;
  font-weight: bold;
  color: var(--foreground);
}

.search-bar-desktop {
  display: none;
  flex: 1;
  max-width: 35%;
}

@media (min-width: 768px) {
  .search-bar-desktop {
    display: block;
  }
}

.search-input {
  width: 100%;
}

.search-input :deep(.el-input__inner) {
  height: 32px;
  font-size: 13px;
  background-color: rgba(26, 28, 31, 0.5);
  border-color: var(--border);
}

.header-actions {
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

.wallet-balance-desktop {
  display: none;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-2) var(--space-3);
  border-radius: var(--radius-md);
  background-color: rgba(26, 28, 31, 0.5);
  border: 1px solid var(--border);
  font-size: 13px;
  font-weight: 600;
  color: var(--foreground);
}

@media (min-width: 768px) {
  .wallet-balance-desktop {
    display: flex;
  }
}

.deposit-btn {
  height: 32px;
  padding: 0 var(--space-4);
  font-size: 12px;
  font-weight: 600;
}

.login-btn-desktop {
  display: none;
  height: 32px;
  padding: 0 var(--space-3);
  font-size: 13px;
}

@media (min-width: 768px) {
  .login-btn-desktop {
    display: inline-flex;
  }
}

.signup-btn {
  height: 32px;
  padding: 0 var(--space-4);
  font-size: 12px;
  font-weight: 600;
}

.user-btn {
  display: none;
  width: 32px;
  height: 32px;
}

@media (min-width: 768px) {
  .user-btn {
    display: inline-flex;
  }
}
</style>

// v0_source/components/header.tsx
"use client"

import { Search, User, Wallet, LogIn } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useState } from "react"
import WalletModal from "./wallet-modal"

export default function Header() {
  const [isLoggedIn, setIsLoggedIn] = useState(true)
  const [walletOpen, setWalletOpen] = useState(false)

  return (
    <>
      <header className="sticky top-0 z-50 border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80">
        <div className="mx-auto max-w-[1400px] px-3 md:px-4 py-1.5 md:py-1.5">
          <div className="flex items-center justify-between gap-3 md:gap-4">
            {/* Logo */}
            <div className="flex items-center gap-1.5 shrink-0">
              <div className="flex h-7 w-7 md:h-7 md:w-7 items-center justify-center rounded-lg bg-gradient-to-br from-accent to-accent-secondary">
                <div className="text-[13px] font-bold text-foreground">#</div>
              </div>
              <span className="text-sm md:text-base font-bold tracking-tight text-foreground">FairHash</span>
            </div>

            {/* Search Bar - 32-40% width on desktop */}
            <div className="hidden md:flex flex-1 max-w-[35%]">
              <div className="relative w-full">
                <Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" />
                <Input
                  type="search"
                  placeholder="Search games..."
                  className="h-8 pl-9 bg-secondary/50 border-border/50 text-[13px] rounded-lg focus-visible:ring-primary/50"
                />
              </div>
            </div>

            {/* Right Actions */}
            <div className="flex items-center gap-1.5 md:gap-2">
              {isLoggedIn ? (
                <>
                  <div className="hidden md:flex items-center gap-1.5 rounded-lg bg-secondary/50 px-2.5 py-1 border border-border/50">
                    <Wallet className="h-3.5 w-3.5 text-primary" />
                    <span className="text-[13px] font-semibold text-foreground">$1,250.00</span>
                  </div>
                  <Button
                    onClick={() => setWalletOpen(true)}
                    className="h-8 md:h-8 px-3 md:px-4 bg-primary hover:bg-primary/90 text-primary-foreground font-semibold text-[12px] md:text-[13px] rounded-lg shadow-sm"
                  >
                    Deposit
                  </Button>
                  <Button variant="ghost" size="icon" className="hidden md:flex h-8 w-8">
                    <User className="h-[18px] w-[18px]" />
                  </Button>
                </>
              ) : (
                <>
                  <Button variant="ghost" className="hidden md:flex h-8 px-3 text-[13px] gap-1.5">
                    <LogIn className="h-3.5 w-3.5" />
                    Login
                  </Button>
                  <Button className="h-8 px-3 md:px-4 bg-gradient-to-r from-accent to-accent-secondary hover:opacity-90 text-foreground font-semibold text-[12px] md:text-[13px] rounded-lg shadow-sm">
                    Sign Up
                  </Button>
                  <Button
                    variant="outline"
                    className="hidden md:flex h-8 px-3 text-[13px] border-primary/50 text-primary hover:bg-primary/10 bg-transparent"
                  >
                    Quick Demo
                  </Button>
                </>
              )}
            </div>
          </div>
        </div>
      </header>

      <WalletModal open={walletOpen} onOpenChange={setWalletOpen} />
    </>
  )
}
